version : "3"

services:
  webapp:
      build:
        context: webapp
      ports:
        - "5000"
  
  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - webapp
      ports:
        - "80:80"